### ISSUE TITLE
XK is missing

### ISSUE THREAD

**Issue by Najada** [alcohol/iso3166#101]
XK is missing, which is the code of Kosovo. Would it be possible to add it?

**Comment by alcohol** [comment]
It's part of the user assigned codes, which so far I have intentionally not implemented.

https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#User-assigned_code_elements

I can add a decorator that offers the extended codes, similar to how the aliases decorator works (but different).

**Comment by EnterVPL** [comment]
I created the PR https://github.com/alcohol/iso3166/pull/109 - checkout

**Comment by alcohol** [comment]
While I am still not sure if it belongs in the main dataset; I have no strong objections to adding it I guess.

**Comment by EnterVPL** [comment]
I think adding a decorator will help, because sometimes companies like Mastercard support different codes, and you have to support it somehow
See: https://developer.mastercard.com/card-issuance/documentation/code-and-formats/iso-country-and-currency-codes/
not all codes from the link are correct.

EDIT: example: in Mastercard Kosovo has: `Kosovo	900	QZ	QZZ`

**Comment by alcohol** [comment]
I think that is something that belongs in userland code though, not this library.

**Comment by EnterVPL** [comment]
Of course, but the easiest way would be to inherit ISO3166, but it is final now

**Comment by alcohol** [comment]
Yes, that is intentional.

**Comment by EnterVPL** [comment]
I see release 4.3.2 with Kosovo, but in https://packagist.org/packages/league/iso3166 version is not updated. Can you refresh it?

**Comment by alcohol** [comment]
I don't release as `league` anymore, sorry.

**Comment by alcohol** [comment]
Ah wait, it was simply pointing to the wrong repo. I think it's resolved now.

**Comment by EnterVPL** [comment]
composer update successfully 😄 
Thakns 🎉 💪🏼
