### ISSUE TITLE
Consider removing `phpunit/php-invoker` as a dependency

### ISSUE THREAD

**Issue by nikolaposa** [alcohol/iso3166#13]
ext-pcntl library is not installed by default in many PHP environments and support for this feature requires a recompile of PHP.

That being said, perhaps `phpunit/php-invoker` shouldn't be used as a dependency. 

btw Not even sure whether its features are used in unit tests of this library at the moment.

**Comment by alcohol** [comment]
It is not used. It is an old relic that I had totally forgotten about. Thanks for pointing it out.
