### ISSUE TITLE
Is there any documentation?

### ISSUE THREAD

**Issue by rap2hpoutre** [alcohol/iso3166#25]
Is there any documentation?

**Comment by alcohol** [comment]
No, I created #5 as a joke.

**Comment by frankdejonge** [comment]
@alcohol haven't had your morning coffee yet? :neckbeard:

**Comment by alcohol** [comment]
Sorry, it just seems kind of hard to miss it, as the list of open issues really is not that long yet, and documentation is clearly there :p

I have been slacking. Have not had time to actually document the API yet. Need to add it to the `gh-pages` branch so it will show up on https://iso3166.thephpleague.com/
