### ISSUE TITLE
BYN for Belarus?

### ISSUE THREAD

**Issue by drcreazy** [alcohol/iso3166#35]
Hi,
thanks for such great package.

It seems to BYN currency should be added to Belarus https://en.wikipedia.org/wiki/Belarusian_ruble 
Is the currencies referrers to some ISO? 
I'll check for BYN then

**Comment by alcohol** [comment]
You are correct. Thank you for spotting this. I will merge your PR and tag a new release :-)

**Comment by alcohol** [comment]
Hmm I also have a lot of other changes.. think I will need to do some trickery here to create both a patch version and a new major version.

**Comment by alcohol** [comment]
1.0.2 has been released.
