### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by enumag** [alcohol/iso3166#39]
I see that the stable version 1.0.x has a different API than the master branch:

```php
// 1.0.x
$data = (new League\ISO3166\ISO3166)->getByAlpha2($alpha2);
// master
$data = (new League\ISO3166\ISO3166)->alpha2($alpha2);
```

The [documentation](https://iso3166.thephpleague.com/using) describes the master API with no hint that it is different in stable.

Also the documentation should contain an example of what the `$data` variable contains.

**Comment by alcohol** [comment]
Yeah I should get around to tagging a new version. I think I was just about done with the changes I had in mind, but then a lot of other projects and work came up and I kind of forgot..

**Comment by alcohol** [comment]
Tagged `2.0.0`.
