### ISSUE TITLE
Vehicle registration codes

### ISSUE THREAD

**Issue by arnested** [alcohol/iso3166#4]
Hi,

Thank you for a usable library.

Besides the functionality in your library I also need to lookup country by [vehicle registration codes](https://en.wikipedia.org/wiki/List_of_international_vehicle_registration_codes).

I have not been able to locate such a library though. Since it is somewhat related I was wondering whether you know such a library?

Alternatively do you think it would be a suitable change to your library to include those as well? I can offer to create a pull request with the data.

Kind regards,
Arne

**Comment by alcohol** [comment]
Hi @arnested,

I do not know of one, nor was I able to quickly find one.

I do not think it would be suitable to change this library to include the relevant data.

I would however be willing to create a new library that specifically offers the "International Registration Letter" or "International Circulation Mark" data.

Please let me know if you would be interested in the latter. Of course, you are completely welcome to create such a library yourself as well. Whichever is more convenient.

Kind regards,
Rob

**Comment by arnested** [comment]
Yeah, it would be kind of an odd child in this library so I understand your reason not to include it.

I'm not 100% sure if I'll need it yet. If I'll need I could also build it myself -- although I would probably end up running out of time and make a rough implementation tightly coupled to my current project (currently the client isn't sure if their existing data actually _is_ vehicle registration codes or just loosely based on them).

Thank you for you feedback / opinion. I'll let you know if I end up needing it and if I create an implementation myself.

**Comment by alcohol** [comment]
No problem, good luck with everything.
