### ISSUE TITLE
Region, sub-region and region codes

### ISSUE THREAD

**Issue by OzzyCzech** [alcohol/iso3166#40]
Hi there,

will be possible add region, sub-region and region codes?

There are some great resources about that: https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes

Roman

**Comment by alexander-schranz** [comment]
I also built a resource for subdivisions: https://github.com/alexander-schranz/iso-3166-2

**Comment by alcohol** [comment]
This package was originally put together to only offer 3166-1 data. I do confess the name of this package was perhaps a poor choice in hindsight regarding that. I am not sure how much work it would be to supplement the existing data with 3166-2 (and maybe even 3166-3 potentially). On top of that, it would have to be kept up to date, which is probably an even bigger task. I am not sure I have the time for either :-(

**Comment by OzzyCzech** [comment]
ok, thanks
