### ISSUE TITLE
Missing countries

### ISSUE THREAD

**Issue by WimWidgets** [alcohol/iso3166#41]
I've gotten an **OutOfBoundsException** for the following alpha-2 codes:
- AC
- IC
- EA
- DG
- EZ
- XK
- TA
- UN

So you might want to update your data.

**Comment by alcohol** [comment]
It would be helpful if you specify which countries these belong to.

The following do not exist on https://en.wikipedia.org/wiki/ISO_3166-1:

- AC
- IC
- EA
- DG
- EZ
- XK
- TA
- UN

( in short, every single alpha-2 code you listed does not exist there )

**Comment by alcohol** [comment]
They also don't exist in the official listing at https://www.iso.org/obp/ui/#search

In short, my data is valid, and your claims are not backed up by any facts.

**Comment by WimWidgets** [comment]
My bad. It seems the internationalization package I'm using throws in a couple more countries which are not globally agreed upon. So much for International Standards...
