### ISSUE TITLE
Missing ANT iso code

### ISSUE THREAD

**Issue by rafalmnich** [alcohol/iso3166#42]
There is missing an ANT (Netherlands Antille) ISO code. Regarding this article:
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3#Transitional_reservations
It's beeing reserved.

**Comment by alcohol** [comment]
Yeah, but for the purpose of this library, it's irrelevant. I only care about existing valid codes, not ones that are deprecated. The new codes are already available in this library so there is no need for a transitional path.
