### ISSUE TITLE
country code for kosovo is added

### ISSUE THREAD

**Issue by galion96** [alcohol/iso3166#54]
it appears that library does not have support for iso3code for Kosovo, and since the class is marked final it can not be extended to add the data manually

**Comment by alcohol** [comment]
https://en.wikipedia.org/wiki/Kosovo still considers Kosovo to be disputed and there is no official code in the standard, only a user assigned one.

https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2 states

> The code XK is being used by the European Commission, the IMF, and SWIFT, CLDR and other organizations as a temporary country code for Kosovo.

So I'm reluctant to add it, since it is not yet part of the official standard.

**Comment by galion96** [comment]
I understand, what do you think about not making the class final, so it can be extended if someone wants to add some "disputed" countries or ect

**Comment by alcohol** [comment]
I see no reason to remove the `final`. While you cannot extend it, you can still wrap it. The difference is minor, if not nihil.

**Comment by galion96** [comment]
Thats what I already did was just a suggestion, thanks and I will mark this resolved.
