### ISSUE TITLE
Include other countries

### ISSUE THREAD

**Issue by paolooo** [alcohol/iso3166#55]
Hi,

Is it possible to include other countries such as countries of the UK - England, Scotland, Wales, and Northern Ireland?

I can see those countries in wiki (see the link below) but it doesn't have some ISO 3166-1 and 3166-2 data.
https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes

Thoughts?

**Comment by alcohol** [comment]
If you really want those additional "countries", you can always decorate this library with your own class to extend the dataset.

**Comment by paolooo** [comment]
Ok, thanks. :)

**Comment by alexandrmazur96** [comment]
> you can always decorate this library with your own class to extend the dataset.

Just to be honest - he can't. No one can – https://3v4l.org/2mVuc#v8.2.5

The dataset in `ISO3166` has a `private` visibility modifier - https://github.com/thephpleague/iso3166/blob/74a08ffe08d4e0dd8ab0aac8c34ea5a641d57669/src/ISO3166.php#L160

**Comment by alcohol** [comment]
You're talking about extending, not decorating.
