### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by mruz** [alcohol/iso3166#58]
```
  Problem 4
    - Installation request for league/iso3166 2.1.5 -> satisfiable by league/iso3166[2.1.5].
    - league/iso3166 2.1.5 requires php ^7.0 -> your PHP version (8.0.0) does not satisfy that requirement.
```
https://github.com/thephpleague/iso3166/blob/350dda73d4006296bd404ce6115c14217f40b5a4/composer.json#L11

**Comment by mruz** [comment]
https://github.com/thephpleague/iso3166/pull/57

**Comment by nostadt** [comment]
There's an open PR for PHP 8 support https://github.com/thephpleague/iso3166/pull/57
