### ISSUE TITLE
Antarctica data incomplete/questionable

### ISSUE THREAD

**Issue by heiglandreas** [alcohol/iso3166#6]
I'm pretty sure Antarctica has not only Norwegian Krones as a currency. 

According to https://en.wikipedia.org/wiki/Antarctica there are different country-calling-codes and currencies depending on the area/station/base on the continent. 

So the entry in https://github.com/thephpleague/iso3166/blob/master/src/ISO3166.php#L215 should perhaps be altered...

**Comment by alcohol** [comment]
Yeah Antarctica is a bit of an odd duck. Difficult to find a good reliable source.

**Comment by alcohol** [comment]
http://althistory.wikia.com/wiki/List_of_Currencies_in_Antarctica_(Great_White_South) seems rather complete.

**Comment by heiglandreas** [comment]
OK. It looks like I'm not getting the joke.... Cause that list is everything but real.

**Comment by heiglandreas** [comment]
[Here](https://en.wikipedia.org/wiki/Research_stations_in_Antarctica#Research_stations) is a list of stations and their states currencies are valid currencies in their respective territory. But I might be wrong on that...

**Comment by alcohol** [comment]
That looks more reasonable indeed.

It's going to take some reading to figure out which currencies that actually boils down to...

---

Update; looks like the following countries, I will add their respective currencies:
- Argentina
- Australia
- Belarus
- Belgium
- Brazil
- Bulgaria
- Chile
- China
- Czech Republic
- Ecuador
- Finland
- France
- Germany
- India
- Italy
- Japan
- New Zealand
- Norway
- Pakistan
- Peru
- Poland
- Romania
- Russia
- South Afrika
- South Korea
- Spain
- Sweden
- Ukraine
- United Kingdom
- United States
- Uruguay
