### ISSUE TITLE
[Not an issue] GetByName / GetByCountryName

### ISSUE THREAD

**Issue by tobeorla** [alcohol/iso3166#6]
¿Couldn't that be possible?

**Comment by alcohol** [comment]
Technically, yes it is possible. But this can easily be implemented by the end-user through extending the base class, if they really desire this behaviour. It is not very intuitive. Some of the names are not commonly used in an informal setting. It might require partial matching for countries such as the UK for example (which people might shorten to United Kingdom, but is indexed as "United Kingdom of Great Britain and Northern Ireland").
