### ISSUE TITLE
"Czech Republic" or "Czechia" (Alias -feature request)

### ISSUE THREAD

**Issue by cottton** [alcohol/iso3166#68]
Just run into that.
Wiki: since 2016 Czechia is official.

Thought i just ask if there would be a chance to add an alias - 
So if i get (user) input `Czech Republic` it points to `Czechia` internally.

**Comment by alcohol** [comment]
Wikipedia denotes it as a short-form alias. Not the official representation. If you want to use a custom alias, perhaps https://github.com/thephpleague/iso3166/issues/61#issuecomment-808105868 could be of use to you.

**Comment by 8ctopus** [comment]
See https://github.com/thephpleague/iso3166/pull/76

**Comment by mrceperka** [comment]
I have the same problem. Can someone approve and merge PR if possible please? Thanks

**Comment by alcohol** [comment]
Merged #76
