### ISSUE TITLE
PHP 8.1 Deprecation message

### ISSUE THREAD

**Issue by repat** [alcohol/iso3166#69]
I'm getting this deprecation warning using PHP 8.1

> Return type of League\ISO3166\ISO3166::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /xyz/vendor/league/iso3166/src/ISO3166.php

Could you fix this please? :) Thanks!

**Comment by alcohol** [comment]
But the return type already is `int`? What version are you using?

**Comment by repat** [comment]
Sorry, nevermind, another dependency downgraded it to 3.0. Seems ok in 4.
