### ISSUE TITLE
Missed Netherlands Antilles (feature request)

### ISSUE THREAD

**Issue by nkoptel** [alcohol/iso3166#71]
https://www.iso.org/obp/ui/#iso:code:3166:AN
iso2: AN
iso3 ANT

**Comment by alcohol** [comment]
Maybe you missed the news.. https://en.wikipedia.org/wiki/Dissolution_of_the_Netherlands_Antilles

See also the remark on the website of iso.org:

> The Netherlands Antilles was divided into Bonaire, Saint Eustatius and Saba (BQ, BES,
535), Curaçao (CW, CUW, 531) and Sint Maarten (Dutch part) (SX, SXM, 534).

**Comment by nkoptel** [comment]
Thanks!
