### ISSUE TITLE
Missing entry for Canary Islands

### ISSUE THREAD

**Issue by ppaulis** [alcohol/iso3166#80]
Currently, there is no entry for Canary Islands:
https://www.iso.org/obp/ui/#iso:code:3166:IC

The PR #79 adds the missing entry.

Thanks!
Best regards,
Pascal

**Comment by alcohol** [comment]
It is reserved but not an official entry afaik. I am not certain if it makes sense to add it, because it also exists as a [subdivision](https://en.wikipedia.org/wiki/ISO_3166-2:ES) of Spain, which falls under ISO-3166-2 specifically (not implemented in this library).

**Comment by ppaulis** [comment]
In that case, I'll close the PR :-)
That's for the explanation!
