### ISSUE TITLE
Croatia currency updated in 2023

### ISSUE THREAD

**Issue by aclare92** [alcohol/iso3166#89]
Under recent changes, Croatia is now using the Euro;

[https://www.sail-croatia.com/resources/currency-in-croatia](url)

> As of January 2023, the currency used in Croatia is the Euro. Prior to this change, Croatia’s official currency was the Croatian Kuna (HRK) between 1994 and 2023

Thanks. Amazing work here from everyone!

**Comment by alcohol** [comment]
Done in https://github.com/thephpleague/iso3166/commit/ce8c18bc55ee7a29fa63a532e9238e894201a7fa
