### ISSUE TITLE
Test class can be

### ISSUE THREAD

**Issue by harikt** [alcohol/iso3166#9]
moved outside of src. 

It helps composer dumpautoload -o flag I believe. As you are good in it I don't need to tell more on it .

**Comment by alcohol** [comment]
You are correct, though the difference is only noticable if you perform a `--prefer-source` install (or install `dev-master`). The **dist** release does not include the test file, so an optimized autoload dump will only contain the interface and class.

I'll move it for clarity :-)

**Comment by harikt** [comment]
@alcohol I am not a fan of removing the tests from vendor folder when installing release.

People want to install using --prefer-source then or dev-master which is really harmful.  I have sometimes used certain test classes of other 3rd party libraries to extend my test cases. 

I know this topic is debatable, but I prefer tests to be given as part of code on installation. It has nothing to do with download speed or disk space.
