### ISSUE TITLE
Make ISO3166 more "extendable"

### ISSUE THREAD

**Issue by alexandrmazur96** [alcohol/iso3166#90]
Unfortunately, because `ISO3166` have `private` visibility modifier on its internal "dataset" ($countries) – 

https://github.com/thephpleague/iso3166/blob/74a08ffe08d4e0dd8ab0aac8c34ea5a641d57669/src/ISO3166.php#L160

we can do nothing to provide more library custom functionality in the project.

For example, we need to consider the `CI` (Canary Islands) country code as Spain, so one of the possible solutions for that is to include `CI` in the dataset, but I can't extend it without copy-paste the whole `ISO3166` class.

Raising the visibility level to `protected` will allow me to extend your class and modify the dataset for my needs. Moreover, it does not even look like BC.

**Comment by alcohol** [comment]
You can decorate the class.
