### ISSUE TITLE
Multibyte string extension does not described in composer.json schema.

### ISSUE THREAD

**Issue by alexandrmazur96** [alcohol/iso3166#92]
The most valuable methods in `ISO3166` class rely on multibyte string comparisons:
https://github.com/thephpleague/iso3166/blob/74a08ffe08d4e0dd8ab0aac8c34ea5a641d57669/src/ISO3166.php#L140-L153

So I think the library should describe `ext-mbstring` as a required extension in the `composer.json` schema.

**Comment by alcohol** [comment]
Fair enough.
